services:
  reemission:
    build:
      context: .
    image: ghcr.io/tomjanus/reemission:release
    volumes:
      - ./examples:/home/appuser/reemission/examples
      - ./outputs:/home/appuser/reemission/outputs
    stdin_open: true 
    tty: true
