services:
  geocaret:
    build:
      context: .
    image: ghcr.io/reservoir-research/geocaret:release
    volumes:
      - ${GEOCARET_AUTH_PATH:-./auth}:/home/appuser/.config
      - ./data:/home/appuser/geocaret/data
      - ./outputs:/home/appuser/geocaret/outputs
    stdin_open: true 
    tty: true
